version: '3'

services:
  golang:
    build: .
    ports:
      - "8080:8080"
    container_name: golang
    command: sh -c "cd app && bee run -downdoc=true -gendoc=true"
    volumes:
      - ./app:/go/src/github.com/app
